name: Deploy to Droplet

on:
  push:
    branches:
      - main # Trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Latest stable as of now

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Build and push Docker image
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_HOST_KEY }}" >> ~/.ssh/known_hosts  # Add host key
          echo "${{ secrets.DROPLET_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key
          docker build -t chez-ayhan .
          docker save chez-ayhan | ssh -i deploy_key root@207.154.244.48 "docker load"

      - name: Deploy on Droplet
        run: |
          ssh -i deploy_key root@207.154.244.48 << 'EOF'
            docker stop chez-ayhan || true
            docker rm chez-ayhan || true
            docker run -d --name chez-ayhan -p 3000:3000 chez-ayhan
          EOF

      - name: Clean up
        run: rm -f deploy_key
